server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gkd
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: GharKiDukanAuth

jwt:
  secret: my-super-secret-key-GHARKIDUKAN-ABCDEFGHIKLMNOPQRSTUVWXYZ
  expiration: 3600000 # 1 hour in ms
